name: Report package.json on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  report-package-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y jq curl

      - name: Definir variables
        id: vars
        run: |
          DEP="axios"
          PROJECT_NAME=$(jq -r .name package.json)
          VERSION=$(jq -r ".dependencies[\"$DEP\"] // .devDependencies[\"$DEP\"]" package.json)
          BASE_BRANCH_NAME=$GITHUB_BASE_REF

          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BASE_BRANCH_NAME=$BASE_BRANCH_NAME" >> $GITHUB_ENV

      - name: Paso 1 - Enviar proyecto
        id: proyecto
        run: |
          echo "🔹 Enviando proyecto: $PROJECT_NAME"
          RESPONSE=$(curl -s -X POST https://c6ff-2800-486-990-5300-9819-4655-136c-a392.ngrok-free.app/proyectos \
            -H "Content-Type: application/json" \
            -d "{\"nombre\": \"${PROJECT_NAME}\"}")
          echo "Respuesta: $RESPONSE"
          PROJECT_ID=$(echo "$RESPONSE" | jq -r '.id')
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV

      - name: Paso 2 - Enviar rama
        id: rama
        run: |
          echo "🔹 Enviando rama: $BASE_BRANCH_NAME"
          RESPONSE=$(curl -s -X POST https://c6ff-2800-486-990-5300-9819-4655-136c-a392.ngrok-free.app/rama \
            -H "Content-Type: application/json" \
            -d "{\"nombre\": \"${BASE_BRANCH_NAME}\", \"proyectoId\": ${PROJECT_ID}}")
          echo "Respuesta: $RESPONSE"
          RAMA_ID=$(echo "$RESPONSE" | jq -r '.id')
          echo "RAMA_ID=$RAMA_ID" >> $GITHUB_ENV

      - name: Paso 3 - Enviar versión
        id: version
        run: |
          echo "🔹 Enviando versión: $VERSION"
          curl -s -X POST https://c6ff-2800-486-990-5300-9819-4655-136c-a392.ngrok-free.app/version \
            -H "Content-Type: application/json" \
            -d "{\"numeroVersion\": \"${VERSION}\", \"proyectoId\": ${PROJECT_ID}, \"ramaId\": ${RAMA_ID}}"