name: Report package.json on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  report-package-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Read project info and send to API
        run: |
          DEP="axios"
          PROJECT_NAME=$(jq -r .name package.json)
          VERSION=$(jq -r ".dependencies[\"$DEP\"] // .devDependencies[\"$DEP\"]" package.json)

          if [ "$VERSION" != "null" ]; then
            echo "✅ $DEP está en el proyecto con versión: $VERSION"
            curl -X POST https://3ec8-2800-486-990-5300-9819-4655-136c-a392.ngrok-free.app/proyectos \
              -H "Content-Type: application/json" \
              -d "{\"nombre\": \"${PROJECT_NAME}\", \"version\": \"${VERSION}\"}"
          else
            echo "❌ $DEP no está instalado. No se enviará nada."
          fi